/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CriarConta`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/terms`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Calculos` | `/Calculos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Principal` | `/Principal`; params?: Router.UnknownInputParams; } | { pathname: `/form/[cropId]/AreaStep`, params: Router.UnknownInputParams & { cropId: string | number; } } | { pathname: `/form/[cropId]/CultureStep`, params: Router.UnknownInputParams & { cropId: string | number; } } | { pathname: `/form/[cropId]/SoilStep`, params: Router.UnknownInputParams & { cropId: string | number; } } | { pathname: `/result/[cropId]`, params: Router.UnknownInputParams & { cropId: string | number; } } | { pathname: `/video/[cropId]`, params: Router.UnknownInputParams & { cropId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/CriarConta`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/terms`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Calculos` | `/Calculos`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Principal` | `/Principal`; params?: Router.UnknownOutputParams; } | { pathname: `/form/[cropId]/AreaStep`, params: Router.UnknownOutputParams & { cropId: string; } } | { pathname: `/form/[cropId]/CultureStep`, params: Router.UnknownOutputParams & { cropId: string; } } | { pathname: `/form/[cropId]/SoilStep`, params: Router.UnknownOutputParams & { cropId: string; } } | { pathname: `/result/[cropId]`, params: Router.UnknownOutputParams & { cropId: string; } } | { pathname: `/video/[cropId]`, params: Router.UnknownOutputParams & { cropId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/CriarConta${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/Login${`?${string}` | `#${string}` | ''}` | `/terms${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Calculos${`?${string}` | `#${string}` | ''}` | `/Calculos${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Principal${`?${string}` | `#${string}` | ''}` | `/Principal${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CriarConta`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/terms`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Calculos` | `/Calculos`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Principal` | `/Principal`; params?: Router.UnknownInputParams; } | `/form/${Router.SingleRoutePart<T>}/AreaStep` | `/form/${Router.SingleRoutePart<T>}/CultureStep` | `/form/${Router.SingleRoutePart<T>}/SoilStep` | `/result/${Router.SingleRoutePart<T>}` | `/video/${Router.SingleRoutePart<T>}` | { pathname: `/form/[cropId]/AreaStep`, params: Router.UnknownInputParams & { cropId: string | number; } } | { pathname: `/form/[cropId]/CultureStep`, params: Router.UnknownInputParams & { cropId: string | number; } } | { pathname: `/form/[cropId]/SoilStep`, params: Router.UnknownInputParams & { cropId: string | number; } } | { pathname: `/result/[cropId]`, params: Router.UnknownInputParams & { cropId: string | number; } } | { pathname: `/video/[cropId]`, params: Router.UnknownInputParams & { cropId: string | number; } };
    }
  }
}
